# CMake generated Testfile for 
# Source directory: /home/runner/work/dragonfly/dragonfly/src/server
# Build directory: /home/runner/work/dragonfly/dragonfly/_codeql_build_dir/src/server
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tiered_storage_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/tiered_storage_test")
set_tests_properties(tiered_storage_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;69;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(dragonfly_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/dragonfly_test")
set_tests_properties(dragonfly_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;128;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(multi_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/multi_test")
set_tests_properties(multi_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;129;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(generic_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/generic_family_test")
set_tests_properties(generic_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;130;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(hset_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/hset_family_test")
set_tests_properties(hset_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;131;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(list_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/list_family_test")
set_tests_properties(list_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;132;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(server_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/server_family_test")
set_tests_properties(server_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;133;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(set_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/set_family_test")
set_tests_properties(set_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;134;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(stream_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/stream_family_test")
set_tests_properties(stream_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;135;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(string_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/string_family_test")
set_tests_properties(string_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;136;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(bitops_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/bitops_family_test")
set_tests_properties(bitops_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;137;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(rdb_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/rdb_test")
set_tests_properties(rdb_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;138;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(zset_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/zset_family_test")
set_tests_properties(zset_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;142;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(geo_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/geo_family_test")
set_tests_properties(geo_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;143;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(blocking_controller_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/blocking_controller_test")
set_tests_properties(blocking_controller_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;144;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(json_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/json_family_test")
set_tests_properties(json_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;145;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(json_family_memory_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/json_family_memory_test")
set_tests_properties(json_family_memory_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;146;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(journal_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/journal_test")
set_tests_properties(journal_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;147;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(hll_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/hll_family_test")
set_tests_properties(hll_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;148;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(bloom_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/bloom_family_test")
set_tests_properties(bloom_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;149;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(cluster_config_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/cluster_config_test")
set_tests_properties(cluster_config_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;150;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(cluster_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/cluster_family_test")
set_tests_properties(cluster_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;151;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(acl_family_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/acl_family_test")
set_tests_properties(acl_family_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;152;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
add_test(engine_shard_set_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/engine_shard_set_test")
set_tests_properties(engine_shard_set_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;153;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/server/CMakeLists.txt;0;")
subdirs("search")
subdirs("tiering")
