name: Run Tests On Repeat
description: "Repeat specific tests"

inputs:
  dfly-executable:
    required: true
    type: string
  run-only-on-ubuntu-latest:
    required: true
    type: string
  build-folder-name:
    required: true
    type: string
  expression:
    required: false
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
  s3-bucket:
    required: true
    type: string
  count:
    required: true
    type: number
  timeout:
    required: true
    type: string
  epoll:
    required: true
    type: string
  vmodule_expression:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Repeat pytests
      id: main
      shell: bash
      run: |
        ls -l ${GITHUB_WORKSPACE}/
        cd ${GITHUB_WORKSPACE}/build
        ./dragonfly_test --gtest_filter=DflyEngineTest.ZeroAllocationEviction --gtest_repeat=10000 --gtest_break_on_failure
