version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "tools/**"
      - "tests/**"

    open-pull-requests-limit: 1
    groups:
      actions:
        patterns:
          - "*"


  - package-ecosystem: "gomod"
    directories:
      - "/contrib/charts/dragonfly"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 1
    #uncomment it to group dependency updates
    #groups:
      #go-mod:
        #patterns:
          #- "*"
    ignore:
      # Disable all updates except security updates
      #remove an item from ignore list to get dependency updates of that kind
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

