name: Regression Tests
description: "Run regression tests"

inputs:
  dfly-executable:
    required: true
    type: string
  gspace-secret:
    required: false
    type: string
  run-only-on-ubuntu-latest:
    # 'true' or 'false' cause boolean
    # is not supported in composite actions
    required: true
    type: string
  build-folder-name:
    required: true
    type: string
  filter:
    required: false
    type: string
  aws-access-key-id:
    required: false
    type: string
    description: "AWS access key ID (optional if using OIDC - credentials set by workflow)"
  aws-secret-access-key:
    required: false
    type: string
    description: "AWS secret access key (optional if using OIDC - credentials set by workflow)"
  s3-bucket:
    required: true
    type: string
  epoll:
    required: false
    type: string
  df-arg:
    default: ""
    required: false
    type: string

runs:
  using: "composite"
  # bring back timeouts once composite actions start supporting them
  # timeout-minutes: 20
  steps:
    - name: Sync valkey-search tests
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tests/dragonfly/valkey_search
        # main branch revision
        ./sync-valkey-search-tests.sh 90124dc91756b24cb2e58e5c4eea5b8d53004ea6
    - name: Prepare Step
      shell: bash
      run: |
        DOCKER_VERSION="26.1.4"
        RUNNER_ARCH="${{ runner.arch }}"
        if [ "$RUNNER_ARCH" == "X64" ]; then
          ARCH="x86_64"
        elif [ "$RUNNER_ARCH" == "ARM64" ]; then
          ARCH="aarch64"
        else
          echo "Unknown architecture: ${RUNNER_ARCH}"
          exit 1
        fi
        curl -fsSL "https://download.docker.com/linux/static/stable/${ARCH}/docker-${DOCKER_VERSION}.tgz" | tar xz --strip 1 docker/docker -C ./docker
        registry="ghcr.io/romange" && for image in fedora:30 ubuntu:noble; do ./docker pull "$registry/$image"; done
    - name: Free disk space
      if: contains(runner.labels, 'self-hosted') == false
      shell: bash
      run: |
        echo "===================Before freeing up space ============================================"
        df -h
        rm -rf /hostroot/usr/share/dotnet
        rm -rf /hostroot/usr/local/share/boost
        rm -rf /hostroot/usr/local/lib/android
        rm -rf /hostroot/opt/ghc
        echo "===================After freeing up space ============================================"
        df -h

    - name: Run PyTests
      id: main
      shell: bash
      run: |
        ls -l ${GITHUB_WORKSPACE}/
        cd ${GITHUB_WORKSPACE}/tests
        echo "Current commit is ${{github.sha}}"
        pip3 install -r dragonfly/requirements.txt
        # used by PyTests
        export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/${{inputs.build-folder-name}}/${{inputs.dfly-executable}}"
        export ROOT_DIR="${GITHUB_WORKSPACE}/tests/dragonfly/valkey_search"
        export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 # to crash on errors

        if [[ "${{inputs.df-arg}}" == 'experimental_io_loop_v2' ]]; then
          echo "df-arg: experimental io loop v2"
          export DF_ARG="--df experimental_io_loop_v2=true"
        fi

        if [[ "${{inputs.epoll}}" == 'epoll' ]]; then
          export FILTER="${{inputs.filter}} and not exclude_epoll"
          # Run only replication tests with epoll
          timeout 80m pytest -m "$FILTER" --durations=10 --timeout=300 --color=yes --json-report --json-report-file=report.json dragonfly $DF_ARG --df force_epoll=true --log-cli-level=INFO || code=$?
        else
          export FILTER="${{inputs.filter}}"
          # Run only replication tests with iouring
          timeout 80m pytest -m "$FILTER" --durations=10 --timeout=300 --color=yes --json-report --json-report-file=report.json dragonfly $DF_ARG --log-cli-level=INFO || code=$?
        fi

        # timeout returns 124 if we exceeded the timeout duration
        if [[ $code -eq 124 ]]; then
          # Add an extra new line here because when tests timeout the first line below continues from the test failure name
          echo "\n"
          echo "🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑"
          echo "🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 TESTS TIMEDOUT 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑"
          echo "🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑"
          # Copy the last log file because we timedout and pytest did not copy it over
          # the /tmp/failed/ folder
          cat /tmp/last_test_log_dir.txt | xargs -I {} mv {}/ /tmp/failed/
          exit 1
        fi

        # when a test fails in pytest it returns 1 but there are other return codes as well so we just check if the code is non zero
        if [[ $code -ne 0 ]]; then
          exit 1
        fi
      env:
        # Add environment variables to enable the S3 snapshot test.
        # AWS credentials: if inputs provided, use them; otherwise rely on workflow OIDC auth
        DRAGONFLY_S3_BUCKET: ${{ inputs.s3-bucket }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id || env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key || env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ env.AWS_REGION || 'us-east-1' }}

    - name: Send notification on failure
      if: failure() && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        get_failed_tests() {
          local report_file=$1
          echo $(jq -r '.tests[] | select(.outcome == "failed") | .nodeid' "$report_file")
        }
        cd ${GITHUB_WORKSPACE}/tests
        failed_tests=""
        if [ -f report.json ]; then
          failed_tests=$(get_failed_tests report.json)
        fi

        KIND="iouring"
        if [[ "${{inputs.epoll}}" == 'epoll' ]]; then
          KIND="epoll"
        fi

        job_link="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        message="Regression $KIND tests failed.\\n The commit is: ${{github.sha}}.\\n $failed_tests \\n Job Link: ${job_link}\\n"

        curl -s \
          -X POST \
          -H 'Content-Type: application/json' \
          '${{ inputs.gspace-secret }}' \
          -d '{"text": "'"${message}"'"}'
    - name: Copy binary on a self hosted runner
      if: failure() && contains(runner.labels, 'self-hosted')
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/build
        timestamp=$(date +%Y-%m-%d_%H:%M:%S)
        mv ./dragonfly /var/crash/dragonfly_${timestamp}
