extraObjects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: dragonfly-password
  stringData:
    password: foobar

passwordFromSecret:
  enable: true
  existingSecret:
    name: '{{ include "dragonfly.name" $ }}-password'
    key: password
