# CMake generated Testfile for 
# Source directory: /home/runner/work/dragonfly/dragonfly/src/core
# Build directory: /home/runner/work/dragonfly/dragonfly/_codeql_build_dir/src/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dfly_core_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/dfly_core_test")
set_tests_properties(dfly_core_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;41;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(compact_object_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/compact_object_test")
set_tests_properties(compact_object_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;42;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(extent_tree_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/extent_tree_test")
set_tests_properties(extent_tree_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;43;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(dash_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/dash_test")
set_tests_properties(dash_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;44;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(interpreter_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/interpreter_test")
set_tests_properties(interpreter_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;45;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(string_set_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/string_set_test")
set_tests_properties(string_set_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;47;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(string_map_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/string_map_test")
set_tests_properties(string_map_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;48;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(oah_set_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/oah_set_test")
set_tests_properties(oah_set_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;49;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(sorted_map_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/sorted_map_test")
set_tests_properties(sorted_map_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;50;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(bptree_set_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/bptree_set_test")
set_tests_properties(bptree_set_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;51;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(linear_search_map_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/linear_search_map_test")
set_tests_properties(linear_search_map_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;52;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(score_map_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/score_map_test")
set_tests_properties(score_map_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;53;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(flatbuffers_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/flatbuffers_test")
set_tests_properties(flatbuffers_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;54;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(bloom_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/bloom_test")
set_tests_properties(bloom_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;55;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(allocation_tracker_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/allocation_tracker_test")
set_tests_properties(allocation_tracker_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;56;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(qlist_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/qlist_test")
set_tests_properties(qlist_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;57;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(zstd_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/zstd_test")
set_tests_properties(zstd_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;58;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(top_keys_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/top_keys_test")
set_tests_properties(top_keys_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;59;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(page_usage_stats_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/page_usage_stats_test")
set_tests_properties(page_usage_stats_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;60;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(count_min_sketch_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/count_min_sketch_test")
set_tests_properties(count_min_sketch_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;61;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
add_test(memory_test "/home/runner/work/dragonfly/dragonfly/_codeql_build_dir/memory_test")
set_tests_properties(memory_test PROPERTIES  LABELS "DFLY" _BACKTRACE_TRIPLES "/home/runner/work/dragonfly/dragonfly/helio/cmake/internal.cmake;222;add_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;62;helio_cxx_test;/home/runner/work/dragonfly/dragonfly/src/core/CMakeLists.txt;0;")
subdirs("search")
subdirs("json")
subdirs("page_usage")
