name: generate-site
on:
  workflow_dispatch:

jobs:
  gen-site:
    runs-on: ubuntu-latest

    name: Generate index and site assets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install RPM tools
        run: sudo apt install -y rpm gpg createrepo-c dpkg-dev reprepro

      - name: Setup requirements
        working-directory: tools/packaging/osrepos
        run: pip install -r requirements.txt

      - name: Download packages
        working-directory: tools/packaging/osrepos
        run: python scripts/fetch-releases.py

      - name: Import GPG key
        id: gpg-import
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Sign RPMs
        shell: sh
        working-directory: tools/packaging/osrepos
        run: sh scripts/sign-rpms.sh ${{ steps.gpg-import.outputs.fingerprint }}

      - name: Create YUM repository
        shell: sh
        working-directory: tools/packaging/osrepos
        run: createrepo_c -v _site/rpm

      - name: Sign YUM repository
        shell: sh
        working-directory: tools/packaging/osrepos
        run: gpg --armor --detach-sign _site/rpm/repodata/repomd.xml

      - name: Create APT repository
        shell: sh
        working-directory: tools/packaging/osrepos
        run: sh -x scripts/generate-apt-repo.sh

      - name: Prepare assets
        working-directory: tools/packaging/osrepos
        run: |
          cp -aRv dragonfly.repo pgp-key.public dragonfly.sources _site/
          rm -rf _site/deb/conf

      - name: Generate Directory Listings
        working-directory: tools/packaging/osrepos
        run: python scripts/generate-index.py
